# Generated by Django 2.2 on 2019-04-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('avatar', models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('spec', models.IntegerField(default=0)),
                ('birth_date', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('genres', models.CharField(blank=True, default='', max_length=100)),
                ('instruments', models.CharField(blank=True, default='', max_length=200)),
                ('soundcloud', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
