# Generated by Django 2.2 on 2019-05-25 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('group', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('spec', models.IntegerField(default=0)),
                ('birth_date', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('genres', models.CharField(blank=True, default='', max_length=100)),
                ('instruments', models.CharField(blank=True, default='', max_length=200)),
                ('soundcloud', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('followers', models.ManyToManyField(related_name='follows', to='userApp.PersonProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mus', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.EventProfile')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('genres', models.CharField(blank=True, default='', max_length=100)),
                ('instruments', models.CharField(blank=True, default='', max_length=200)),
                ('soundcloud', models.CharField(blank=True, default='', max_length=100)),
                ('create_date', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('users', models.ManyToManyField(to='userApp.PersonProfile')),
            ],
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile'),
        ),
    ]
