# Generated by Django 2.2 on 2019-04-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personprofile',
            old_name='avatar',
            new_name='image',
        ),
    ]
