# Generated by Django 2.2 on 2019-05-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20190525_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
