# Generated by Django 2.2 on 2019-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20190419_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
