# Generated by Django 2.2 on 2019-05-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20190525_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='users',
        ),
    ]
