# Generated by Django 2.2 on 2019-05-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_eventprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile'),
        ),
    ]
