# Generated by Django 2.2 on 2019-05-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20190518_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile'),
        ),
    ]
