# Generated by Django 2.2 on 2019-04-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20190420_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-registertime']},
        ),
    ]
