# Generated by Django 2.2 on 2019-06-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_groupprofile_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', to='userApp.PersonProfile'),
        ),
    ]
