# Generated by Django 2.2 on 2019-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_requestevent_requestgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='groups',
            field=models.ManyToManyField(to='userApp.GroupProfile'),
        ),
    ]
