# Generated by Django 2.2 on 2019-04-23 04:27

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20190422_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='pic_folder'),
        ),
    ]
