# Generated by Django 2.2 on 2019-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20190608_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='userApp.PersonProfile'),
        ),
    ]
