# Generated by Django 2.2 on 2019-05-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20190518_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.EventProfile')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile')),
            ],
        ),
    ]
