# Generated by Django 2.2 on 2019-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20190423_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
