# Generated by Django 2.2 on 2019-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20190518_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_mus',
            field=models.BooleanField(default=False),
        ),
    ]
