# Generated by Django 2.2 on 2019-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20190522_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='followes',
            field=models.ManyToManyField(related_name='follows', to='userApp.PersonProfile'),
        ),
    ]
