# Generated by Django 2.2 on 2019-06-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_acceptedevent_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedevent',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.GroupProfile'),
        ),
    ]
