# Generated by Django 2.2 on 2019-06-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_auto_20190601_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedevent',
            name='group',
        ),
    ]
