# Generated by Django 2.2 on 2019-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_auto_20190426_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='spec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='description',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='phone',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
