# Generated by Django 2.2 on 2019-06-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_remove_acceptedevent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.GroupProfile'),
        ),
        migrations.AlterField(
            model_name='acceptedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile'),
        ),
    ]
