# Generated by Django 2.2 on 2019-06-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_auto_20190601_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.GroupProfile'),
        ),
    ]
