# Generated by Django 2.2 on 2019-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_auto_20190426_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='spec',
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=''),
        ),
    ]
