# Generated by Django 2.2.1 on 2019-06-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_auto_20190601_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprofile',
            name='group',
        ),
    ]
