# Generated by Django 2.2 on 2019-06-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_remove_eventprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='users',
        ),
        migrations.CreateModel(
            name='AcceptedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.GroupProfile')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.PersonProfile')),
            ],
        ),
    ]
