# Generated by Django 2.2 on 2019-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_auto_20190426_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='adress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
