# Generated by Django 2.2 on 2019-06-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_auto_20190608_1013'),
        ('userApp', '0007_auto_20190608_1019'),
    ]

    operations = [
    ]
