# Generated by Django 2.2 on 2019-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_auto_20190426_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
