# Generated by Django 2.2 on 2019-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0018_auto_20190617_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
