# Generated by Django 2.2 on 2019-04-26 12:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0019_auto_20190426_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 12, 6, 7, 820896, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(default=datetime.datetime(2019, 4, 26, 12, 6, 7, 821893, tzinfo=utc))),
                ('phone', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
