# Generated by Django 2.2 on 2019-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0019_auto_20190617_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='image',
            field=models.FileField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
