# Generated by Django 2.2 on 2019-04-26 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0020_auto_20190426_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='genres',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 12, 18, 33, 544213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 12, 18, 33, 543213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
