# Generated by Django 2.2 on 2019-04-26 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0021_auto_20190426_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='instruments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='musicianprofile',
            name='soundcloud',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 12, 41, 1, 880275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 12, 41, 1, 879276, tzinfo=utc)),
        ),
    ]
