# Generated by Django 2.2 on 2019-04-26 14:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0023_auto_20190426_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 14, 26, 3, 795152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 14, 26, 3, 794153, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('company', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
