# Generated by Django 2.2 on 2019-04-26 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0025_auto_20190426_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 28, 34, 417732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='soundcloud',
            field=models.URLField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 28, 34, 416732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
