# Generated by Django 2.2 on 2019-04-26 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0027_auto_20190426_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 32, 33, 725491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 32, 33, 724491, tzinfo=utc)),
        ),
    ]
