# Generated by Django 2.2 on 2019-04-26 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0028_auto_20190426_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 36, 42, 906962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 15, 36, 42, 905962, tzinfo=utc)),
        ),
    ]
