# Generated by Django 2.2 on 2019-04-26 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0029_auto_20190426_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='personprofile',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='instruments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='soundcloud',
            field=models.URLField(blank=True, default='/'),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='spec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 16, 29, 9, 674151, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='MusicianProfile',
        ),
    ]
