# Generated by Django 2.2 on 2019-04-27 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0031_auto_20190426_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 27, 5, 47, 19, 615638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='soundcloud',
            field=models.URLField(blank=True, default=''),
        ),
    ]
