# Generated by Django 2.2 on 2019-04-27 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0032_auto_20190427_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 27, 5, 53, 55, 444840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='soundcloud',
            field=models.URLField(blank=True, default='http/'),
        ),
    ]
