# Generated by Django 2.2 on 2019-04-27 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0033_auto_20190427_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 27, 5, 56, 5, 597705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='soundcloud',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
