# Generated by Django 2.2 on 2019-04-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0034_auto_20190427_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(blank=True, default='2019-01-01'),
        ),
    ]
