# Generated by Django 2.2 on 2019-04-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0035_auto_20190427_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
